//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.Eve.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketGroup
    {
        public MarketGroup()
        {
            this.Items = new HashSet<Item>();
            this.SubGroups = new HashSet<MarketGroup>();
        }
    
        public int MarketGroupId { get; set; }
        public Nullable<int> ParentGroupId { get; set; }
        public string MarketGroupName { get; set; }
        public string Description { get; set; }
        public Nullable<int> IconId { get; set; }
        public Nullable<bool> HasTypes { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual MarketGroup ParentGroup { get; set; }
        public virtual ICollection<MarketGroup> SubGroups { get; set; }
    }
}
